openapi: 3.1.0

info:
  version: 1.0.0
  title: Estimate_M2 OpenAPI
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: This is a documentation of Estimate_M2 app

tags:
  - name: Auth
    description: Auth operations.
  - name: Projects
    description: Operations about projects.

servers:
  - url: http://localhost:3000

paths:
  /auth/register:
    post:
      $ref: ../swagger/paths/auth/register.yaml
  /auth/login:
    post:
      $ref: ../swagger/paths/auth/login.yaml
  /auth/refresh:
    post:
      $ref: ../swagger/paths/auth/refresh.yaml
  /auth/logout:
    post:
      $ref: ../swagger/paths/auth/logout.yaml
  /auth/send-reset-email:
    post:
      $ref: ../swagger/paths/auth/send-reset-email.yaml
  /auth/reset-password:
    post:
      $ref: ../swagger/paths/auth/reset-password.yaml
  /projects:
    post:
      $ref: ../swagger/paths/projects/createProject.yaml

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
